### ISSUE TITLE
Battery Level ?

### ISSUE THREAD

**Issue by vincegre** [nplan/HomeButtons#8]
Hi

It would be nice to be able to get battery level and charging status ;) Currently it's not reported by firmware in info page but not sure if it's hw or software restriction there :/
Out of it great fan of it, just received mine today :+1: 

Thanks

Vincèn

**Comment by nplan** [comment]
The battery level can be seen by activating info screen (2 second press, see [here](https://docs.home-buttons.com/user_guide/#info_screen)), or on devices page in Home Assistant.

Charging status is currently (HW rev 2.2) not available due to hardware limitations. But you will get a message on screen, when it's fully charged. See [here](https://docs.home-buttons.com/setup/#charging). 

Does this answer your question?
