### ISSUE TITLE
Question (not an issue) - Have you considered double-click functionality?

### ISSUE THREAD

**Issue by Koendejongh** [nplan/HomeButtons#9]
Hi,

Is it possible to add double-click functionality to home buttons?

Thanks,
Koen

**Comment by nplan** [comment]
No, not at the moment. It's on the list of future improvements.

**Comment by nplan** [comment]
Added this feature in v2.0.1-beta. It works slightly differently than what @gon0 suggested to be compatible with Home Assistant. There is now a separate topic and a separate trigger entity for single, double, triple and quadruple press. The payload is still "PRESS" in all cases. He LEDs flash the number of presses. Hold functionality is not implemented since it's used for controlling other features of Home Buttons.

**Comment by MatthiasLohr** [comment]
> The LEDs flash the number of presses

Can't confirm that.

Single: LED just on
Double: LED just on
Triple: LED on - off - on
Quadruple: LED on - off - on - off - on

**Comment by nplan** [comment]
In sleep mode the last blink always holds until device goes back to sleep. In awake mode all blinks are the same length.

Is it actually registering the correct number of presses and just blinking wrong?

You might be clicking too quickly. See issue #26.

**Comment by MatthiasLohr** [comment]
> You might be clicking too quickly. See issue #26.

Oh, yes! Giving it a bit more time and it works.
